version: 2.1

orbs:
  c: rafaelostertag/common-orb@1.19.0

workflows:
  version: 2
  build-any-branch:
    jobs:
      - c/maven-build-and-test:
          name: build-and-test
          sonar-project-key: "ch.guengel.astro:astro-lib"
          context:
            - sonar
            - repository-read
      - c/maven-deploy-artifacts:
          filters:
            branches:
              only:
                - master
          name: deploy-maven-artifacts
          requires:
            - build-and-test
          context:
            - maven-repository-write

  daily-dependency-check:
    triggers:
      - schedule:
          cron: "21 4 * * 4"
          filters:
            branches:
              only:
                - master
                - develop

    jobs:
      - c/maven-dependency-check:
          context:
            - repository-read
